// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qbdherUoFi-mI2rTmLq7ignhZtR8ruA',
    appId: '1:993166224200:web:aa2a0c28069cc8eba3217d',
    messagingSenderId: '993166224200',
    projectId: 'devmuscles-353ee',
    authDomain: 'devmuscles-353ee.firebaseapp.com',
    storageBucket: 'devmuscles-353ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkY5AQ6EcxNEeVVn7k_qUv1dXeyc53v4',
    appId: '1:993166224200:android:d40583c3794e2e9fa3217d',
    messagingSenderId: '993166224200',
    projectId: 'devmuscles-353ee',
    storageBucket: 'devmuscles-353ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNpw7ua37ruEGyBatNJpPtwU1cgy8LoQ',
    appId: '1:993166224200:ios:cf40da8874d2d7a2a3217d',
    messagingSenderId: '993166224200',
    projectId: 'devmuscles-353ee',
    storageBucket: 'devmuscles-353ee.appspot.com',
    iosBundleId: 'com.example.fitnessClup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNpw7ua37ruEGyBatNJpPtwU1cgy8LoQ',
    appId: '1:993166224200:ios:cf40da8874d2d7a2a3217d',
    messagingSenderId: '993166224200',
    projectId: 'devmuscles-353ee',
    storageBucket: 'devmuscles-353ee.appspot.com',
    iosBundleId: 'com.example.fitnessClup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qbdherUoFi-mI2rTmLq7ignhZtR8ruA',
    appId: '1:993166224200:web:f239a7f8ea3c957da3217d',
    messagingSenderId: '993166224200',
    projectId: 'devmuscles-353ee',
    authDomain: 'devmuscles-353ee.firebaseapp.com',
    storageBucket: 'devmuscles-353ee.appspot.com',
  );
}
